### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Slapbox** [sfrieson/circular-dependency-plugin-visualizer#4]
It occurs at the end of the `<script>` tag, in the line that starts, `root.appendChild(plot(`

**Comment by Slapbox** [comment]
```js
  root.appendChild(plot(width, height {...}
                                                        ^ missing comma
```

**Comment by sfrieson** [comment]
Thank you very much for this bug report, @Slapbox. The issue has been patched by @vparchas. I unfortunately missed it when he first put up the MR.

The patch has been [published to npm](https://www.npmjs.com/package/circular-dependency-plugin-visualizer) (v 1.1.1).

**Comment by Slapbox** [comment]
Thanks very much to you @sfrieson for the great project and the very speedy release! And thanks to @vparchas!
